### ISSUE TITLE
Firewalld fails on systems with non-modular kernels

### ISSUE THREAD

**Issue by alexkingnz** [firewalld/firewalld#1000]
**What happened**:
On a VPS with a monolithic kernel, after loading firewalld I see the following traceback in the journal:
```
Jul 21 03:00:46 test.domu.build.rimuhosting.com firewalld[26579]: Traceback (most recent call last):
                                                                    File "/usr/lib/python3.6/site-packages/firewall/server/decorators.py", line 67, in dbus_handle_exceptions
                                                                      return func(*args, **kwargs)
                                                                    File "/usr/lib/python3.6/site-packages/firewall/server/firewalld.py", line 335, in completeReload
                                                                      self.fw.reload(True)
                                                                    File "/usr/lib/python3.6/site-packages/firewall/core/fw.py", line 1092, in reload
                                                                      raise start_exception
                                                                    File "/usr/lib/python3.6/site-packages/firewall/core/fw.py", line 1010, in reload
                                                                      self._start(reload=True, complete_reload=stop)
                                                                    File "/usr/lib/python3.6/site-packages/firewall/core/fw.py", line 444, in _start
                                                                      self.modules_backend.unload_firewall_modules()
                                                                    File "/usr/lib/python3.6/site-packages/firewall/core/modules.py", line 99, in unload_firewall_modules
                                                                      for module in self.get_firewall_modules():
                                                                    File "/usr/lib/python3.6/site-packages/firewall/core/modules.py", line 79, in get_firewall_modules
                                                                      (mods2, deps) = self.loaded_modules()
                                                                    File "/usr/lib/python3.6/site-packages/firewall/core/modules.py", line 43, in loaded_modules
                                                                      with open("/proc/modules", "r") as f:
                                                                  FileNotFoundError: [Errno 2] No such file or directory: '/proc/modules'
```
`firewall-cmd --state` shows `failed`
No traffic is able to be received on port 80, while I believe configuration is in place to allow that, if only firewalld were functional.

**What you expected to happen**:
No traceback, A state other than "failed" in response to `firewall-cmd --state`  A functional firewall.

**How to reproduce it (as minimally and precisely as possible)**:
Reboot with a non-modular kernel.  Or test on a hosting provider who use that by default.

**Environment**:
```
# dnf info firewalld
Last metadata expiration check: 3:18:53 ago on Thu 21 Jul 2022 22:18:50 UTC.
Installed Packages
Name         : firewalld
Version      : 0.9.3
Release      : 13.el8
Architecture : noarch
Size         : 2.0 M
Source       : firewalld-0.9.3-13.el8.src.rpm
Repository   : @System
From repo    : baseos
Summary      : A firewall daemon with D-Bus interface providing a dynamic
             : firewall
URL          : http://www.firewalld.org
License      : GPLv2+
Description  : firewalld is a firewall service daemon that provides a dynamic
             : customizable firewall with a D-Bus interface.

# cat /etc/firewalld/firewalld.conf | grep FirewallBackend
# FirewallBackend
FirewallBackend=nftables

# cat /etc/os-release 
NAME="Rocky Linux"
VERSION="8.6 (Green Obsidian)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.6"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Rocky Linux 8.6 (Green Obsidian)"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:rocky:rocky:8:GA"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
ROCKY_SUPPORT_PRODUCT="Rocky Linux"
ROCKY_SUPPORT_PRODUCT_VERSION="8"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8"

# uname -a
Linux test.domu.build.rimuhosting.com 4.19.0-really250-rh288-20220703010735.xenU.x86_64 #1 SMP Sun Jul 3 01:08:06 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by alexkingnz** [comment]
Issue https://github.com/firewalld/firewalld/issues/430 used to break firewalld on such systems.  A fix for this was provided.  This appears to be a new issue.

**Comment by erig0** [comment]
> Issue #430 used to break firewalld on such systems. A fix for this was provided. This appears to be a new issue.

Looks like #430 fixed _built in_ modules, e.g. built in nf_conntrack. But did not address kernels where `CONFIG_MODULES=n`.
