### ISSUE TITLE
Error: INVALID_ENTRY overlaps entry - ipset is empty or rest data is skipped

### ISSUE THREAD

**Issue by ZIT2050** [firewalld/firewalld#1035]
### What happened

During loading data into ipset when similar nets/subnets is met FirewallD exit with error and ipset is empty or rest is skipped.  
_Error: INVALID_ENTRY: Entry '2.16.0.0/13' overlaps entry '2.16.172.0/24'_

### What you expected to happen

In older version default behavior was to skip duplicates/similar subnets or even don't care about it and load data, so the result was ipset is not empty.

### How to reproduce it (as minimally and precisely as possible)

Use any available IP lists from ipdeny or ip2location and try to mix them or just add a line with lower subnet
https://www.ipdeny.com/ipblocks/data/countries/us.zone

```
$ IPSET=America; IPSET_TYPE="hash:net"; IPSET_MAX=200;
$ firewall-cmd --permanent --new-ipset=${IPSET} --type=${IPSET_TYPE} --option=maxelem=${IPSET_MAX}

```
One file
```
america.lst
27.100.36.0/22
36.255.24.0/22
43.198.0.0/15
27.100.36.0/24
66.42.32.0/19
69.161.221.0/24
85.113.70.0/23
```
```
$ firewall-cmd --permanent --ipset=${IPSET} --add-entries-from-file=america.lst
Error: INVALID_ENTRY: Entry '27.100.36.0/22' overlaps entry '27.100.36.0/24'
$ firewall-cmd --permanent --ipset=${IPSET} --get-entries
(null)
```

Many files
```
america1.lst
27.100.36.0/22
36.255.24.0/22
43.198.0.0/15
```

```
america2.lst
27.100.36.0/24
66.42.32.0/19
69.161.221.0/24
85.113.70.0/23
```

```

$ firewall-cmd --permanent --ipset=${IPSET} --add-entries-from-file=america1.lst
success
$ firewall-cmd --permanent --ipset=${IPSET} --add-entries-from-file=america2.lst
Error: INVALID_ENTRY: Entry '27.100.36.0/22' overlaps entry '27.100.36.0/24
$ firewall-cmd --permanent --ipset=${IPSET} --get-entries
27.100.36.0/22
36.255.24.0/22
43.198.0.0/15

```

I expect that ipset contains all of them. But after error the rest of second file is skipped.

### Anything else we need to know?

Trying to remove/empty ipset
```
$ firewall-cmd --permanent --ipset=${IPSET} --get-entries
27.100.36.0/22
36.255.24.0/22
43.198.0.0/15
43.200.0.0/13
43.208.0.0/13
43.216.0.0/14
```

`$ firewall-cmd --permanent --ipset=${IPSET} --get-entries >> remove.lst`
```
$ firewall-cmd --permanent --ipset=${IPSET} --remove-entries-from-file=remove.lst
Error: Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/firewall/client.py", line 55, in handle_exceptions
    return func(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/firewall/client.py", line 1621, in setEntries
    check_for_overlapping_entries(entries)
  File "/usr/lib/python3.6/site-packages/firewall/core/ipset.py", line 379, in check_for_overlapping_entries
    prev_network = entries.pop(0)
IndexError: pop from empty list
```
```
firewall-cmd --permanent --delete-ipset=${IPSET};
success
```

### Firewalld Version

firewalld-0.9.3-13.el8

### Firewalld Backend

iptables

### Linux distribution

Rocky Linux 8.6 (Green Obsidian)

### Linux kernel version

4.18.0-372.26.1.el8_6.x86_64

**Comment by ZIT2050** [comment]
Thank you @erig0 
Please clarify me - **all** FirewallD **versions newer then** firewalld-0.9.3-13.el8 **work the same with this error** Error: INVALID_ENTRY **?** Treat the same as an error and exit and don't load anything?  
Then it is completly new behavior of FirewallD not like in the older version. Then if you use ipsets in scripts, your firewall maybe useless because ipset are empty or no complete. Is this logic right?

For me it means all admins over the world should normalize list of entries first ...
