### ISSUE TITLE
avoid Python stack dump when config file is malformed

### ISSUE THREAD

**Issue by HughR** [firewalld/firewalld#1190]
### What would you like to be added

When I created a bad config, the log file said so but also included a stack dump.
The coordinates of the  error in the config file would be useful but I guess --check-config can do that.

Here's an example:
```
Aug 06 02:29:40 my-hostname systemd[1]: Starting firewalld.service - firewalld - dynamic firewall daemon...
Aug 06 02:29:40 my-hostname systemd[1]: Started firewalld.service - firewalld - dynamic firewall daemon.
Aug 06 02:29:40 my-hostname audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=firewalld comm="systemd" exe="/usr/lib>
Aug 06 02:29:40 my-hostname firewalld[17576]: ERROR: Failed to load user configuration. Falling back to full stock configuration.
Aug 06 02:29:40 my-hostname audit[17576]: NETFILTER_CFG table=firewalld:13 family=1 entries=1 op=nft_register_table pid=17576 subj=system_u:system_r:firewalld_t:s0 comm="firewa>
Aug 06 02:29:40 my-hostname audit[17576]: NETFILTER_CFG table=firewalld:14 family=1 entries=222 op=nft_register_chain pid=17576 subj=system_u:system_r:firewalld_t:s0 comm="fire>
Aug 06 02:29:40 my-hostname firewalld[17576]: Traceback (most recent call last):
                                                       File "/usr/lib/python3.11/site-packages/firewall/server/decorators.py", line 51, in _impl
                                                         return func(*args, **kwargs)
                                                                ^^^^^^^^^^^^^^^^^^^^^
                                                       File "/usr/lib/python3.11/site-packages/firewall/server/firewalld.py", line 91, in start
                                                         return self.fw.start()
                                                                ^^^^^^^^^^^^^^^
                                                       File "/usr/lib/python3.11/site-packages/firewall/core/fw.py", line 656, in start
                                                         raise original_exAug 06 02:29:40 my-hostname systemd[1]: Starting firewalld.service - firewalld - dynamic firewall daemon...
Aug 06 02:29:40 my-hostname systemd[1]: Started firewalld.service - firewalld - dynamic firewall daemon.
Aug 06 02:29:40 my-hostname audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=firewalld comm="systemd" exe="/usr/lib>
Aug 06 02:29:40 my-hostname firewalld[17576]: ERROR: Failed to load user configuration. Falling back to full stock configuration.
Aug 06 02:29:40 my-hostname audit[17576]: NETFILTER_CFG table=firewalld:13 family=1 entries=1 op=nft_register_table pid=17576 subj=system_u:system_r:firewalld_t:s0 comm="firewa>
Aug 06 02:29:40 my-hostname audit[17576]: NETFILTER_CFG table=firewalld:14 family=1 entries=222 op=nft_register_chain pid=17576 subj=system_u:system_r:firewalld_t:s0 comm="fire>
Aug 06 02:29:40 my-hostname firewalld[17576]: Traceback (most recent call last):
                                                       File "/usr/lib/python3.11/site-packages/firewall/server/decorators.py", line 51, in _impl
                                                         return func(*args, **kwargs)
                                                                ^^^^^^^^^^^^^^^^^^^^^
                                                       File "/usr/lib/python3.11/site-packages/firewall/server/firewalld.py", line 91, in start
                                                         return self.fw.start()
                                                                ^^^^^^^^^^^^^^^
                                                       File "/usr/lib/python3.11/site-packages/firewall/core/fw.py", line 656, in start
                                                         raise original_ex
                                                       File "/usr/lib/python3.11/site-packages/firewall/core/fw.py", line 633, in start
                                                         self._start()
                                                       File "/usr/lib/python3.11/site-packages/firewall/core/fw.py", line 584, in _start
                                                         self._start_load_user_config()
                                                       File "/usr/lib/python3.11/site-packages/firewall/core/fw.py", line 410, in _start_load_user_config
                                                         self._loader_policies(config.ETC_FIREWALLD_POLICIES)
                                                       File "/usr/lib/python3.11/site-packages/firewall/core/fw.py", line 716, in _loader_policies
                                                         obj = policy_reader(filename, path)
                                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                       File "/usr/lib/python3.11/site-packages/firewall/core/io/policy.py", line 1075, in policy_reader
                                                         parser.parse(source)
                                                       File "/usr/lib64/python3.11/xml/sax/expatreader.py", line 111, in parse
                                                         xmlreader.IncrementalParser.parse(self, source)
                                                       File "/usr/lib64/python3.11/xml/sax/xmlreader.py", line 125, in parse
                                                         self.feed(buffer)
                                                       File "/usr/lib64/python3.11/xml/sax/expatreader.py", line 217, in feed
                                                         self._parser.Parse(data, isFinal)
                                                       File "/builddir/build/BUILD/Python-3.11.4/Modules/pyexpat.c", line 416, in StartElement
                                                       File "/usr/lib64/python3.11/xml/sax/expatreader.py", line 333, in start_element
                                                         self._cont_handler.startElement(name, AttributesImpl(attrs))
                                                       File "/usr/lib/python3.11/site-packages/firewall/core/io/policy.py", line 993, in startElement
                                                         if common_startElement(self, name, attrs):
                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                       File "/usr/lib/python3.11/site-packages/firewall/core/io/policy.py", line 117, in common_startElement
                                                         attrs["value"])
                                                         ~~~~~^^^^^^^^^
                                                       File "/usr/lib64/python3.11/xml/sax/xmlreader.py", line 318, in __getitem__
                                                         return self._attrs[name]
                                                                ~~~~~~~~~~~^^^^^^
                                                     KeyError: 'value'

                                                       File "/usr/lib/python3.11/site-packages/firewall/core/fw.py", line 633, in start
                                                         self._start()
                                                       File "/usr/lib/python3.11/site-packages/firewall/core/fw.py", line 584, in _start
                                                         self._start_load_user_config()
                                                       File "/usr/lib/python3.11/site-packages/firewall/core/fw.py", line 410, in _start_load_user_config
                                                         self._loader_policies(config.ETC_FIREWALLD_POLICIES)
                                                       File "/usr/lib/python3.11/site-packages/firewall/core/fw.py", line 716, in _loader_policies
                                                         obj = policy_reader(filename, path)
                                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                       File "/usr/lib/python3.11/site-packages/firewall/core/io/policy.py", line 1075, in policy_reader
                                                         parser.parse(source)
                                                       File "/usr/lib64/python3.11/xml/sax/expatreader.py", line 111, in parse
                                                         xmlreader.IncrementalParser.parse(self, source)
                                                       File "/usr/lib64/python3.11/xml/sax/xmlreader.py", line 125, in parse
                                                         self.feed(buffer)
                                                       File "/usr/lib64/python3.11/xml/sax/expatreader.py", line 217, in feed
                                                         self._parser.Parse(data, isFinal)
                                                       File "/builddir/build/BUILD/Python-3.11.4/Modules/pyexpat.c", line 416, in StartElement
                                                       File "/usr/lib64/python3.11/xml/sax/expatreader.py", line 333, in start_element
                                                         self._cont_handler.startElement(name, AttributesImpl(attrs))
                                                       File "/usr/lib/python3.11/site-packages/firewall/core/io/policy.py", line 993, in startElement
                                                         if common_startElement(self, name, attrs):
                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                       File "/usr/lib/python3.11/site-packages/firewall/core/io/policy.py", line 117, in common_startElement
                                                         attrs["value"])
                                                         ~~~~~^^^^^^^^^
                                                       File "/usr/lib64/python3.11/xml/sax/xmlreader.py", line 318, in __getitem__
                                                         return self._attrs[name]
                                                                ~~~~~~~~~~~^^^^^^
                                                     KeyError: 'value'

```

### Why is this needed

I think that the dump is distracting and confusing to users.

**Comment by thom311** [comment]
I think this will be fixed by https://github.com/firewalld/firewalld/pull/1187
