### ISSUE TITLE
Missing interfaces

### ISSUE THREAD

**Issue by AlessandroPerucchi** [firewalld/firewalld#223]
Hello,
I'm using CentOS 7.3.1611 and firewalld 0.4.3.2.
NetworkManager is not installed.
I am running in a LXC container.
I have 3 interfaces:

```
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet X.Y.Z.A  netmask 255.255.255.240  broadcast *****
        inet6 ******  prefixlen 64  scopeid 0x20<link>
        ether *****  txqueuelen 1000  (Ethernet)
        RX packets 13968  bytes 1654242 (1.5 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 14  bytes 900 (900.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

eth1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet *****  netmask 255.255.0.0  broadcast *****
        inet6 *****  prefixlen 64  scopeid 0x20<link>
        ether *****  txqueuelen 1000  (Ethernet)
        RX packets 81485  bytes 135039990 (128.7 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 52534  bytes 7632694 (7.2 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1  (Local Loopback)
        RX packets 7014  bytes 2849996 (2.7 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 7014  bytes 2849996 (2.7 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

But when I use the command `firewall-cmd --list-interfaces` I get only that:
`eth0`

This is a new installation from CentOS.

How can I add the eth1 interface? Is it simply possible?
Is this a bug?

**Comment by AlessandroPerucchi** [comment]
I have installed NetworkManager in case it would help...
and here is what I have:

```
# sudo nmcli dev
DEVICE  TYPE      STATE      CONNECTION
eth0    ethernet  connected  System eth0
eth1    ethernet  connected  System eth1
lo      loopback  unmanaged  --
```

and

```
# firewall-cmd --list-interfaces
ERROR:dbus.proxies:Introspect error on :1.8:/org/fedoraproject/FirewallD1: dbus.exceptions.DBusException: org.freedesktop.DBus.Python.ValueError: Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/dbus/service.py", line 707, in _message_cb
    retval = candidate_method(self, *args, **keywords)
  File "/usr/lib/python2.7/site-packages/slip/dbus/service.py", line 148, in wrapped_method
    reply_handler=reply_handler, error_handler=error_handler)
  File "/usr/lib/python2.7/site-packages/slip/dbus/polkit.py", line 270, in IsSystemBusNameAuthorizedAsync
    reply_handler, error_handler, challenge, details)
  File "/usr/lib/python2.7/site-packages/slip/dbus/polkit.py", line 256, in IsSystemBusNameAuthorizedAsync
    timeout=method_call_no_timeout)
  File "/usr/lib64/python2.7/site-packages/dbus/proxies.py", line 137, in __call__
    **keywords)
  File "/usr/lib64/python2.7/site-packages/dbus/connection.py", line 584, in call_async
    message.append(signature=signature, *args)
ValueError: Unable to guess signature from an empty dict

Error: Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/dbus/service.py", line 707, in _message_cb
    retval = candidate_method(self, *args, **keywords)
  File "/usr/lib/python2.7/site-packages/slip/dbus/service.py", line 148, in wrapped_method
    reply_handler=reply_handler, error_handler=error_handler)
  File "/usr/lib/python2.7/site-packages/slip/dbus/polkit.py", line 270, in IsSystemBusNameAuthorizedAsync
    reply_handler, error_handler, challenge, details)
  File "/usr/lib/python2.7/site-packages/slip/dbus/polkit.py", line 256, in IsSystemBusNameAuthorizedAsync
    timeout=method_call_no_timeout)
  File "/usr/lib64/python2.7/site-packages/dbus/proxies.py", line 137, in __call__
    **keywords)
  File "/usr/lib64/python2.7/site-packages/dbus/connection.py", line 584, in call_async
    message.append(signature=signature, *args)
ValueError: Unable to guess signature from an empty dict

```

**Comment by AlessandroPerucchi** [comment]
Ok, I've rebooted, and now I see all my interfaces...

so I need to install NetworkManager apparently...

the question would be now... Is it possible to use firewalld without NetworkManager?
I wish I could avoid using that software...

**Comment by erig0** [comment]
You **can** use firewalld without NetworkManager. Please read the documentation on Zones here: http://www.firewalld.org/documentation/zone/connections-interfaces-and-sources.html. Specifically "Network connections handled by network scripts".
