### ISSUE TITLE
Centos 7 ImportError: No module named firewall.client

### ISSUE THREAD

**Issue by dirkdeb** [firewalld/firewalld#232]
The command sudo firewall-cmd --list-all-zones, and for that matter any other  firewall-cmd produce the following output:
Traceback (most recent call last):
  File "/bin/firewall-cmd", line 31, in <module>
    from firewall.client import FirewallClient, FirewallClientIPSetSettings, \
ImportError: No module named firewall.client

I did a yum reinstall firewalld-0.4.3.2-8.1.el7_3.3.noarch  but still the same results.
I expect some rule got screwed.

How can I fix my boboo.
Thanx

**Comment by t-woerner** [comment]
firewall.client is part of python-firewall in RHEL-7.

**Comment by erig0** [comment]
drikdeb, did installing python-firewall fix your issue?

**Comment by valq7711** [comment]
```
16:55 ~ $ yum install firewalld-0.6.3-11.el7
Loaded plugins: fastestmirror, remove-with-leaves
Loading mirror speeds from cached hostfile
 * base: centos-mirror.rbc.ru
 * elrepo: mirror.yandex.ru
 * epel: mirror.logol.ru
 * extras: mirrors.datahouse.ru
 * updates: mirrors.datahouse.ru
Resolving Dependencies
--> Running transaction check
---> Package firewalld.noarch 0:0.6.3-11.el7 will be installed
--> Processing Dependency: python-firewall = 0.6.3-11.el7 for package: firewalld-0.6.3-11.el7.noarch
--> Processing Dependency: firewalld-filesystem = 0.6.3-11.el7 for package: firewalld-0.6.3-11.el7.noarch
--> Processing Dependency: ipset for package: firewalld-0.6.3-11.el7.noarch
--> Processing Dependency: ebtables for package: firewalld-0.6.3-11.el7.noarch
--> Running transaction check
---> Package ebtables.x86_64 0:2.0.10-16.el7 will be installed
---> Package firewalld-filesystem.noarch 0:0.6.3-11.el7 will be installed
---> Package ipset.x86_64 0:7.1-1.el7 will be installed
--> Processing Dependency: ipset-libs(x86-64) = 7.1-1.el7 for package: ipset-7.1-1.el7.x86_64
--> Processing Dependency: libipset.so.13(LIBIPSET_4.8)(64bit) for package: ipset-7.1-1.el7.x86_64
--> Processing Dependency: libipset.so.13(LIBIPSET_2.0)(64bit) for package: ipset-7.1-1.el7.x86_64
--> Processing Dependency: libipset.so.13()(64bit) for package: ipset-7.1-1.el7.x86_64
---> Package python-firewall.noarch 0:0.6.3-11.el7 will be installed
--> Processing Dependency: python-slip-dbus for package: python-firewall-0.6.3-11.el7.noarch
--> Running transaction check
---> Package ipset-libs.x86_64 0:7.1-1.el7 will be installed
---> Package python-slip-dbus.noarch 0:0.4.0-4.el7 will be installed
--> Processing Dependency: python-slip = 0.4.0-4.el7 for package: python-slip-dbus-0.4.0-4.el7.noarch
--> Running transaction check
---> Package python-slip.noarch 0:0.4.0-4.el7 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

====================================================================================================
 Package                         Arch              Version                    Repository       Size
====================================================================================================
Installing:
 firewalld                       noarch            0.6.3-11.el7               base            448 k
Installing for dependencies:
 ebtables                        x86_64            2.0.10-16.el7              base            123 k
 firewalld-filesystem            noarch            0.6.3-11.el7               base             51 k
 ipset                           x86_64            7.1-1.el7                  base             39 k
 ipset-libs                      x86_64            7.1-1.el7                  base             64 k
 python-firewall                 noarch            0.6.3-11.el7               base            355 k
 python-slip                     noarch            0.4.0-4.el7                base             31 k
 python-slip-dbus                noarch            0.4.0-4.el7                base             32 k

Transaction Summary
====================================================================================================
Install  1 Package (+7 Dependent packages)

Total download size: 1.1 M
Installed size: 4.5 M
Is this ok [y/d/N]: y
Downloading packages:
(1/8): ebtables-2.0.10-16.el7.x86_64.rpm                                     | 123 kB  00:00:00
(2/8): firewalld-0.6.3-11.el7.noarch.rpm                                     | 448 kB  00:00:00
(3/8): ipset-7.1-1.el7.x86_64.rpm                                            |  39 kB  00:00:00
(4/8): firewalld-filesystem-0.6.3-11.el7.noarch.rpm                          |  51 kB  00:00:00
(5/8): ipset-libs-7.1-1.el7.x86_64.rpm                                       |  64 kB  00:00:00
(6/8): python-slip-0.4.0-4.el7.noarch.rpm                                    |  31 kB  00:00:00
(7/8): python-slip-dbus-0.4.0-4.el7.noarch.rpm                               |  32 kB  00:00:00
(8/8): python-firewall-0.6.3-11.el7.noarch.rpm                               | 355 kB  00:00:00
----------------------------------------------------------------------------------------------------
Total                                                               3.7 MB/s | 1.1 MB  00:00:00
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installing : ebtables-2.0.10-16.el7.x86_64                                                    1/8
  Installing : ipset-libs-7.1-1.el7.x86_64                                                      2/8
  Installing : ipset-7.1-1.el7.x86_64                                                           3/8
  Installing : python-slip-0.4.0-4.el7.noarch                                                   4/8
  Installing : python-slip-dbus-0.4.0-4.el7.noarch                                              5/8
  Installing : python-firewall-0.6.3-11.el7.noarch                                              6/8
  Installing : firewalld-filesystem-0.6.3-11.el7.noarch                                         7/8
  Installing : firewalld-0.6.3-11.el7.noarch                                                    8/8
  Verifying  : ipset-7.1-1.el7.x86_64                                                           1/8
  Verifying  : python-firewall-0.6.3-11.el7.noarch                                              2/8
  Verifying  : firewalld-filesystem-0.6.3-11.el7.noarch                                         3/8
  Verifying  : firewalld-0.6.3-11.el7.noarch                                                    4/8
  Verifying  : python-slip-0.4.0-4.el7.noarch                                                   5/8
  Verifying  : python-slip-dbus-0.4.0-4.el7.noarch                                              6/8
  Verifying  : ipset-libs-7.1-1.el7.x86_64                                                      7/8
  Verifying  : ebtables-2.0.10-16.el7.x86_64                                                    8/8

Installed:
  firewalld.noarch 0:0.6.3-11.el7

Dependency Installed:
  ebtables.x86_64 0:2.0.10-16.el7                firewalld-filesystem.noarch 0:0.6.3-11.el7
  ipset.x86_64 0:7.1-1.el7                       ipset-libs.x86_64 0:7.1-1.el7
  python-firewall.noarch 0:0.6.3-11.el7          python-slip.noarch 0:0.4.0-4.el7
  python-slip-dbus.noarch 0:0.4.0-4.el7

Complete!
16:56 ~ $ firewall-cmd --state
Traceback (most recent call last):
  File "/usr/bin/firewall-cmd", line 31, in <module>
    from firewall.client import FirewallClient, FirewallClientIPSetSettings, \
ImportError: No module named firewall.client
```
