### ISSUE TITLE
ERROR: Failed to load service file '/usr/lib/firewalld/servii ces/steam-streaming.xml'

### ISSUE THREAD

**Issue by mbiebl** [firewalld/firewalld#356]
When running firewalld with a non-UTF8 locale (in my case it was POSIX), I get the following failure when starting the daemon:
```
2018-07-26 23:04:38 ERROR: Failed to load service file '/usr/lib/firewalld/services/steam-treaming.xml':
2018-07-26 23:04:38 Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/firewall/core/fw.py", line 530, in _loader
    obj = service_reader(filename, path)
  File "/usr/lib/python3/dist-packages/firewall/core/io/service.py", line 224, in service_reader
    parser.parse(f)
  File "/usr/lib/python3.6/xml/sax/expatreader.py", line 111, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/lib/python3.6/xml/sax/xmlreader.py", line 123, in parse
    buffer = file.read(self._bufsize)
  File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 350: ordinal not in range(128)
```

**Comment by erig0** [comment]
There are a couple unicode right single quotation marks in this service definition. The quick fix is to convert these to ASCII apostrophe. We should really be able to handle unicode in these definitions for non-utf8 locales. I'll make a note to take a look at this. In the mean time I'll push the quick fix below.

```
$ git diff                                                                                                                       
diff --git a/config/services/steam-streaming.xml b/config/services/steam-streaming.xml                                                                                      
index 84b4b23acc16..0e0aca62a90e 100644
--- a/config/services/steam-streaming.xml
+++ b/config/services/steam-streaming.xml
@@ -1,7 +1,7 @@
 <?xml version="1.0" encoding="utf-8"?>
 <service>
   <short>Steam In-Home Streaming</short>
-  <description>Steam in-home streaming allows you to play a game on one computer when the game process is actually running on another computer elsewhere in your home. Through Steam, game audio and video is captured on the remote computer and sent to the player’s computer. The game input (keyboard, mouse or gamepad) is sent from the player’s computer to the game process on the remote computer.</description>                                                                                                            
+  <description>Steam in-home streaming allows you to play a game on one computer when the game process is actually running on another computer elsewhere in your home. Through Steam, game audio and video is captured on the remote computer and sent to the player's computer. The game input (keyboard, mouse or gamepad) is sent from the player's computer to the game process on the remote computer.</description>
   <port protocol="tcp" port="27036"/>
   <port protocol="tcp" port="27037"/>
   <port protocol="udp" port="27031"/>
```

```
$ file config/services/steam-streaming.xml                                                                                         
config/services/steam-streaming.xml: XML 1.0 document, ASCII text, with very long lines
```
