### ISSUE TITLE
firewall/core/fw_nm: nm_get_zone_of_connection returns False

### ISSUE THREAD

**Issue by Farenjihn** [firewalld/firewalld#370]
Hello,

I use NetworkManager which automatically creates a connection for the `docker0` interface. In its current state, `nm_get_zone_of_connection` will return `False` for a generated connection and thus trigger a `ValueError` when running `firewall-config` (in `update_active_zones`).

It seems to me that `nm_get_zone_of_connection` should either not return a Boolean in case of error or each call should check whether it has succeeded before carrying along with string comparisons.

Here is the trace for reference:

```
Traceback (most recent call last):
  File "/bin/firewall-config", line 8093, in <module>
    app = FirewallConfig()
  File "/bin/firewall-config", line 1386, in __init__
    self.connection_changed()
  File "/bin/firewall-config", line 1692, in connection_changed
    self.update_active_zones()
  File "/bin/firewall-config", line 2464, in update_active_zones
    connection, zone ])
  File "/usr/lib/python3.7/site-packages/gi/overrides/Gtk.py", line 1245, in append
    return self._do_insert(parent, -1, row)
  File "/usr/lib/python3.7/site-packages/gi/overrides/Gtk.py", line 1237, in _do_insert
    row, columns = self._convert_row(row)
  File "/usr/lib/python3.7/site-packages/gi/overrides/Gtk.py", line 876, in _convert_row
    result.append(self._convert_value(cur_col, value))
  File "/usr/lib/python3.7/site-packages/gi/overrides/Gtk.py", line 894, in _convert_value
    return GObject.Value(self.get_column_type(column), value)
  File "/usr/lib/python3.7/site-packages/gi/overrides/GObject.py", line 218, in __init__
    self.set_value(py_value)
  File "/usr/lib/python3.7/site-packages/gi/overrides/GObject.py", line 274, in set_value
    (py_value, type(py_value)))
ValueError: Expected string but got False<class 'bool'>
```

Am I missing something?

Thanks

**Comment by erig0** [comment]
Fixed by #373.
