### ISSUE TITLE
dependency for firewall-config

### ISSUE THREAD

**Issue by dkebler** [firewalld/firewalld#389]
Sorry for asking here but forum login is broken

I am running firewall-config from latest source (ubuntu xenial) but get this error
```
sysadmin@router:/opt/firewalld/src$ ./firewall-config
Traceback (most recent call last):
  File "./firewall-config", line 28, in <module>
    gi.require_version('Gtk', '3.0')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 106, in require_version
    (namespace, version))
ValueError: Namespace Gtk not available for version 3.0
```
here are the GtK packages installed on my machine.
What package am I missing here???
```
gir1.2-gtk-2.0/xenial-updates,now 2.24.30-1ubuntu1.16.04.2 arm64 [installed,automatic]
gtk2-engines-murrine/xenial-updates,now 0.98.2-0ubuntu2.2 arm64 [installed,automatic]
libcanberra-gtk-module/xenial,now 0.30-2.1ubuntu1 arm64 [installed,automatic]
libcanberra-gtk0/xenial,now 0.30-2.1ubuntu1 arm64 [installed,automatic]
libdbusmenu-gtk3-4/xenial-updates,now 16.04.1+16.04.20160927-0ubuntu1 arm64 [installed,automatic]
libdbusmenu-gtk4/xenial-updates,now 16.04.1+16.04.20160927-0ubuntu1 arm64 [installed,automatic]
libgtk-3-0/xenial-updates,now 3.18.9-1ubuntu3.3 arm64 [installed,automatic]
libgtk-3-bin/xenial-updates,now 3.18.9-1ubuntu3.3 arm64 [installed,automatic]
libgtk-3-common/xenial-updates,now 3.18.9-1ubuntu3.3 all [installed,automatic]
libgtk2.0-0/xenial-updates,now 2.24.30-1ubuntu1.16.04.2 arm64 [installed,automatic]
libgtk2.0-bin/xenial-updates,now 2.24.30-1ubuntu1.16.04.2 arm64 [installed,automatic]
libgtk2.0-common/xenial-updates,now 2.24.30-1ubuntu1.16.04.2 all [installed,automatic]
libgtkmm-2.4-1v5/xenial,now 1:2.24.4-2 arm64 [installed,automatic]
libgtksourceview2.0-0/xenial,now 2.10.5-2ubuntu2 arm64 [installed,automatic]
libgtksourceview2.0-common/xenial,now 2.10.5-2ubuntu2 all [installed,automatic]
libjavascriptcoregtk-4.0-18/xenial-security,xenial-updates,now 2.20.5-0ubuntu0.16.04.1 arm64 [installed,automatic]
libwebkit2gtk-4.0-37/xenial-security,xenial-updates,now 2.20.5-0ubuntu0.16.04.1 arm64 [installed,automatic]
python-gtk2/xenial,now 2.24.0-4ubuntu1 arm64 [installed,automatic]
python-gtksourceview2/xenial,now 2.10.1-2build1 arm64 [installed,automatic]
```

**Comment by dkebler** [comment]
looks like it's related to my gobject dependency issue #387 .  Maybe me loading python3-gi is not right in which case there must be another package that's correct.

See this. https://askubuntu.com/questions/101306/how-do-i-install-gtk-3-0
```
GTK3 is installed by default, please don't download and compile from the GTK website.

If you want to use GTK3 yourself, compile against that instead GTK2, or use PyGObject instead of PyGTK if you're using Python.

If you want all programs to use GTK3 instead of GTK2, it won't work, it's a job for the application developers to port their application.
```

**Comment by dkebler** [comment]
I installed old version from ubuntu and looks like the missing package is this one `gir1.2-gtk-3.0`.

So now I get a bit farther but still getting an error (does the daemon need be running??)

```
sysadmin@router:/opt/firewalld/src$ ./firewall-config

** (firewall-config:9862): WARNING **: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files

(firewall-config:9862): Gtk-WARNING **: Can't set a parent on widget which has a parent

Traceback (most recent call last):
  File "./firewall-config", line 8089, in <module>
    app = FirewallConfig()
  File "./firewall-config", line 147, in __init__
    self.mainOverlay.add_overlay(self.waitingWindow)
AttributeError: 'NoneType' object has no attribute 'add_overlay'
```

**Comment by erig0** [comment]
It looks like you're missing `python3-gtk3`.

**Comment by dkebler** [comment]
hmm... no package by that name...underlying issue is you all are not developing on ubuntu so packages are not the same :-(.    If/when I get this figured out I'll help with the docs for ubuntu build.

Back to my firewalld dependency issue looks like what is really missing is python3-gobject 
```
sysadmin@router:~$ apt policy python3-gobject
python3-gobject:
  Installed: (none)
  Candidate: (none)
  Version table:
```
Can't believe ubuntu has no candidate just a different name.  Might have build from source.
https://python-gtk-3-tutorial.readthedocs.io/en/latest/install.html.

Anyway if someone has build latest source on ubuntu would sure like to know the dependency list and if any other package had to be build from source.

**Comment by dkebler** [comment]
Sadly I've given up on firewalld for firehol. I upgraded to bionic but firewalld is still way old version and I can't get the dependencies set and I have issues with my kernel and nftables.
