### ISSUE TITLE
“ipset not usable” warning, but IP_SET kernel modules available

### ISSUE THREAD

**Issue by equaeghe** [firewalld/firewalld#591]
I am using firewalld version 0.7.1 on Gentoo.
I get the following warning when looking at the firewalld service status:
```
WARNING: ipset not usable, disabling ipset usage in firewall.
```
However, the IP_SET kernel modules are compiled and available:
```
/usr/src/linux # grep IP_SET .config
CONFIG_IP_SET=m                              
CONFIG_IP_SET_MAX=256                        
CONFIG_IP_SET_BITMAP_IP=m
CONFIG_IP_SET_BITMAP_IPMAC=m
CONFIG_IP_SET_BITMAP_PORT=m
CONFIG_IP_SET_HASH_IP=m
CONFIG_IP_SET_HASH_IPMARK=m
CONFIG_IP_SET_HASH_IPPORT=m
CONFIG_IP_SET_HASH_IPPORTIP=m
CONFIG_IP_SET_HASH_IPPORTNET=m
CONFIG_IP_SET_HASH_IPMAC=m
CONFIG_IP_SET_HASH_MAC=m 
CONFIG_IP_SET_HASH_NETPORTNET=m
CONFIG_IP_SET_HASH_NET=m 
CONFIG_IP_SET_HASH_NETNET=m
CONFIG_IP_SET_HASH_NETPORT=m
CONFIG_IP_SET_HASH_NETIFACE=m
CONFIG_IP_SET_LIST_SET=m 
```
```
/lib/modules/4.19.97/kernel/net/netfilter/ipset # ls
ip_set_bitmap_ip.ko     ip_set_hash_ipmark.ko     ip_set_hash_netiface.ko    ip_set.ko
ip_set_bitmap_ipmac.ko  ip_set_hash_ipportip.ko   ip_set_hash_net.ko         ip_set_list_set.ko
ip_set_bitmap_port.ko   ip_set_hash_ipport.ko     ip_set_hash_netnet.ko
ip_set_hash_ip.ko       ip_set_hash_ipportnet.ko  ip_set_hash_netport.ko
ip_set_hash_ipmac.ko    ip_set_hash_mac.ko        ip_set_hash_netportnet.ko
```
On the other hand, the modules are clearly not loaded, whereas other firewall-related modules are:
```
~ # lsmod 
Module                  Size  Used by
nf_tables_set          32768  5
nft_fib_inet           16384  1
nft_fib_ipv4           16384  1 nft_fib_inet
nft_fib_ipv6           16384  1 nft_fib_inet
nft_fib                16384  3 nft_fib_ipv6,nft_fib_ipv4,nft_fib_inet
nft_reject_inet        16384  4
nf_reject_ipv4         16384  1 nft_reject_inet
nf_reject_ipv6         16384  1 nft_reject_inet
nft_reject             16384  1 nft_reject_inet
nft_ct                 16384  10
af_packet              45056  2
nft_chain_nat_ipv6     16384  2
nft_chain_nat_ipv4     16384  2
nf_tables             131072  189 nft_ct,nft_chain_nat_ipv6,nft_chain_nat_ipv4,nft_reject_inet,nft_fib_ipv6,nft_fib_ipv4,nf_tables_set,nft_reject,nft_fib,nft_fib_inet
nfnetlink              16384  1 nf_tables
ebtable_nat            16384  0
ip6table_nat           16384  0
nf_nat_ipv6            16384  2 ip6table_nat,nft_chain_nat_ipv6
ip6table_mangle        16384  0
ip6table_raw           16384  0
ip6table_security      16384  0
iptable_nat            16384  0
nf_nat_ipv4            16384  2 nft_chain_nat_ipv4,iptable_nat
nf_nat                 32768  2 nf_nat_ipv6,nf_nat_ipv4
iptable_mangle         16384  0
iptable_raw            16384  0
iptable_security       16384  0
nf_conntrack           98304  4 nf_nat,nft_ct,nf_nat_ipv6,nf_nat_ipv4
nf_defrag_ipv6         16384  1 nf_conntrack
libcrc32c              16384  2 nf_conntrack,nf_nat
nf_defrag_ipv4         16384  1 nf_conntrack
ebtable_filter         16384  0
ebtables               36864  2 ebtable_nat,ebtable_filter
ip6table_filter        16384  0
ip6_tables             24576  5 ip6table_filter,ip6table_raw,ip6table_nat,ip6table_mangle,ip6table_security
iptable_filter         16384  0
ip_tables              24576  5 iptable_filter,iptable_security,iptable_raw,iptable_nat,iptable_mangle
x_tables               36864  11 ebtables,ip6table_filter,ip6table_raw,iptable_filter,iptable_security,ip6_tables,iptable_raw,ip_tables,ip6table_mangle,ip6table_security,iptable_mangle
evdev                  20480  1
```
What could be the issue?

Given Issue #95 I have checked whether the executable is present:
```
~ # which ipset
/usr/sbin/ipset
```

**Comment by erig0** [comment]
Please check for AVC denials (SELinux). Also try `setenforce 0`, restart firewalld, and try again.

**Comment by equaeghe** [comment]
> Please check for AVC denials (SELinux). Also try `setenforce 0`, restart firewalld, and try again.

I'm not using SELinux. Nothing suspicious in the logs surrounding the warning.

**Comment by nE0sIghT** [comment]
This is also ossue for me with firewalld-0.7.3 on Gentoo:

```
Mar 20 19:32:37 vortex firewalld[509]: WARNING: ipset not usable, disabling ipset usage in firewall.
Mar 20 19:32:37 vortex firewalld[509]: WARNING: LAN: INVALID_TYPE: 'hash:ip' is not supported by ipset., ignoring for run-time.
Mar 20 19:32:37 vortex firewalld[509]: WARNING: LAN_pcs: INVALID_TYPE: 'hash:ip' is not supported by ipset., ignoring for run-time.
Mar 20 19:32:38 vortex firewalld[509]: WARNING: INVALID_IPSET: LAN_pcs
Mar 20 19:32:38 vortex firewalld[509]: WARNING: INVALID_IPSET: LAN_pcs
Mar 20 19:32:38 vortex firewalld[509]: WARNING: INVALID_IPSET: LAN
```
```
zgrep -i ip_set /proc/config.gz 
CONFIG_IP_SET=y
CONFIG_IP_SET_MAX=256
CONFIG_IP_SET_BITMAP_IP=m
CONFIG_IP_SET_BITMAP_IPMAC=m
CONFIG_IP_SET_BITMAP_PORT=m
CONFIG_IP_SET_HASH_IP=y
CONFIG_IP_SET_HASH_IPMARK=y
CONFIG_IP_SET_HASH_IPPORT=y
CONFIG_IP_SET_HASH_IPPORTIP=y
CONFIG_IP_SET_HASH_IPPORTNET=y
CONFIG_IP_SET_HASH_IPMAC=y
CONFIG_IP_SET_HASH_MAC=y
CONFIG_IP_SET_HASH_NETPORTNET=y
CONFIG_IP_SET_HASH_NET=y
CONFIG_IP_SET_HASH_NETNET=y
CONFIG_IP_SET_HASH_NETPORT=y
CONFIG_IP_SET_HASH_NETIFACE=y
CONFIG_IP_SET_LIST_SET=y
```

**Comment by erig0** [comment]
Are you able to manually load the ipset kernel modules with modprobe? Can you run ipset, e.g. "ipset list" ?

**Comment by nE0sIghT** [comment]
I can define ipset manually and ipset modules are compiled-in my kernel (I also tryed to compile them as loadable modules with same effect).

```
root@vortex ~# ipset create test hash:ip
root@vortex ~# ipset add test 111.111.111.111/32
root@vortex ~# ipset list
Name: test
Type: hash:ip
Revision: 4
Header: family inet hashsize 1024 maxelem 65536
Size in memory: 136
References: 0
Number of entries: 1
Members:
111.111.111.111

```

**Comment by erig0** [comment]
Can you enable firewalld debug (launch daemon with --debug=9) and try again? Please post the logs.

**Comment by equaeghe** [comment]
I can run `ipset` manually as well, and the modules are loaded as needed. From the logs, I get (trimmed a bit):
```
2020-03-20 22:27:41 DEBUG2: <class 'firewall.core.ipXtables.ip4tables'>: /sbin/iptables will be using -w10 option.
2020-03-20 22:27:41 DEBUG2: <class 'firewall.core.ipXtables.ip4tables'>: /sbin/iptables-restore will be using  option.
2020-03-20 22:27:41 DEBUG2: <class 'firewall.core.ipXtables.ip6tables'>: /sbin/ip6tables will be using -w10 option.
2020-03-20 22:27:41 DEBUG2: <class 'firewall.core.ipXtables.ip6tables'>: /sbin/ip6tables-restore will be using  option.
2020-03-20 22:27:41 DEBUG2: <class 'firewall.core.ebtables.ebtables'>: /sbin/ebtables-restore /run/firewalld/temp.9v5hcesr: 0
2020-03-20 22:27:41 DEBUG1: start()
2020-03-20 22:27:41 DEBUG1: Loading firewalld config file '/etc/firewalld/firewalld.conf'
2020-03-20 22:27:41 DEBUG1: CleanupOnExit is set to 'True'
2020-03-20 22:27:41 DEBUG1: IPv6 rpfilter is enabled
2020-03-20 22:27:41 DEBUG1: LogDenied is set to 'off'
2020-03-20 22:27:41 DEBUG1: AutomaticHelpers is set to 'system'
2020-03-20 22:27:41 DEBUG1: FirewallBackend is set to 'nftables'
2020-03-20 22:27:41 DEBUG1: FlushAllOnReload is set to 'True'
2020-03-20 22:27:41 DEBUG1: RFC3964_IPv4 is set to 'True'
2020-03-20 22:27:41 DEBUG2: <class 'firewall.core.ipset.ipset'>: /sbin/ipset list
2020-03-20 22:27:41 WARNING: ipset not usable, disabling ipset usage in firewall.
2020-03-20 22:27:41 DEBUG2: <class 'firewall.core.ipXtables.ip4tables'>: /sbin/iptables -w10 -p icmp --help
2020-03-20 22:27:41 DEBUG2: <class 'firewall.core.ipXtables.ip6tables'>: /sbin/ip6tables -w10 -p ipv6-icmp --help
2020-03-20 22:27:41 DEBUG1: ebtables-restore is not supporting the --noflush option, will therefore not be used
2020-03-20 22:27:41 DEBUG1: Conntrack helpers supported by the kernel:
2020-03-20 22:27:41 DEBUG1:   nf_conntrack_sip: sip
2020-03-20 22:27:41 DEBUG1: NAT helpers supported by the kernel:
2020-03-20 22:27:41 DEBUG1:   nf_nat_sip: sip
2020-03-20 22:27:41 DEBUG1: Loading lockdown whitelist
2020-03-20 22:27:41 DEBUG1: Loading ipset file '/etc/firewalld/ipsets/sshguard4.xml'
2020-03-20 22:27:41 WARNING: sshguard4: INVALID_TYPE: 'hash:net' is not supported by ipset., ignoring for run-time.
2020-03-20 22:27:41 DEBUG1: Loading ipset file '/etc/firewalld/ipsets/sshguard6.xml'
2020-03-20 22:27:41 WARNING: sshguard6: INVALID_TYPE: 'hash:net' is not supported by ipset., ignoring for run-time.
2020-03-20 22:27:41 DEBUG1: Loading icmptype file '/usr/lib/firewalld/icmptypes/address-unreachable.xml'
…
2020-03-20 22:27:41 DEBUG1: Loading icmptype file '/usr/lib/firewalld/icmptypes/unknown-option.xml'
2020-03-20 22:27:41 DEBUG1: Loading helper file '/usr/lib/firewalld/helpers/Q.931.xml'
…
2020-03-20 22:27:41 DEBUG1: Loading helper file '/usr/lib/firewalld/helpers/tftp.xml'
2020-03-20 22:27:41 DEBUG1: Loading service file '/usr/lib/firewalld/services/RH-Satellite-6.xml'
…
2020-03-20 22:27:41 DEBUG1: Loading service file '/usr/lib/firewalld/services/zabbix-server.xml'
2020-03-20 22:27:41 DEBUG1: Loading zone file '/usr/lib/firewalld/zones/block.xml'
2020-03-20 22:27:41 DEBUG1: Loading zone file '/usr/lib/firewalld/zones/dmz.xml'
2020-03-20 22:27:41 DEBUG1: Loading zone file '/usr/lib/firewalld/zones/drop.xml'
2020-03-20 22:27:41 DEBUG1: Loading zone file '/usr/lib/firewalld/zones/external.xml'
2020-03-20 22:27:41 DEBUG1: Loading zone file '/usr/lib/firewalld/zones/home.xml'
2020-03-20 22:27:41 DEBUG1: Loading zone file '/usr/lib/firewalld/zones/internal.xml'
2020-03-20 22:27:41 DEBUG1: Loading zone file '/usr/lib/firewalld/zones/public.xml'
2020-03-20 22:27:41 DEBUG1: Loading zone file '/usr/lib/firewalld/zones/trusted.xml'
2020-03-20 22:27:41 DEBUG1: Loading zone file '/usr/lib/firewalld/zones/work.xml'
2020-03-20 22:27:41 DEBUG1: Loading zone file '/etc/firewalld/zones/public.xml'
2020-03-20 22:27:41 DEBUG1:   Overloads zone 'public' ('/usr/lib/firewalld/zones/public.xml')
2020-03-20 22:27:41 DEBUG1: Using default zone 'public'
2020-03-20 22:27:41 DEBUG2: <class 'firewall.core.modules.modules'>: /sbin/modprobe nf_conntrack
2020-03-20 22:27:41 DEBUG1: Flushing rule set
2020-03-20 22:27:41 DEBUG2: <class 'firewall.core.ipXtables.ip4tables'>: /sbin/iptables -w10 -t security -L -n
2020-03-20 22:27:41 DEBUG2: <class 'firewall.core.ipXtables.ip4tables'>: /sbin/iptables -w10 -t raw -L -n
2020-03-20 22:27:41 DEBUG2: <class 'firewall.core.ipXtables.ip4tables'>: /sbin/iptables -w10 -t mangle -L -n
2020-03-20 22:27:41 DEBUG2: <class 'firewall.core.ipXtables.ip4tables'>: /sbin/iptables -w10 -t nat -L -n
2020-03-20 22:27:41 DEBUG2: <class 'firewall.core.ipXtables.ip4tables'>: /sbin/iptables -w10 -t filter -L -n
2020-03-20 22:27:41 DEBUG2: <class 'firewall.core.ipXtables.ip6tables'>: /sbin/ip6tables -w10 -t security -L -n
2020-03-20 22:27:41 DEBUG2: <class 'firewall.core.ipXtables.ip6tables'>: /sbin/ip6tables -w10 -t raw -L -n
2020-03-20 22:27:41 DEBUG2: <class 'firewall.core.ipXtables.ip6tables'>: /sbin/ip6tables -w10 -t mangle -L -n
2020-03-20 22:27:41 DEBUG2: <class 'firewall.core.ipXtables.ip6tables'>: /sbin/ip6tables -w10 -t nat -L -n
2020-03-20 22:27:41 DEBUG2: <class 'firewall.core.ipXtables.ip6tables'>: /sbin/ip6tables -w10 -t filter -L -n
2020-03-20 22:27:41 DEBUG4: <class 'firewall.core.fw_transaction.FirewallTransaction'>.execute(True)
2020-03-20 22:27:41 DEBUG4: <class 'firewall.core.fw_transaction.FirewallTransaction'>.prepare(True, ...)
2020-03-20 22:27:41 DEBUG4: <class 'firewall.core.fw_transaction.FirewallTransaction'>.prepare(True, ...)
2020-03-20 22:27:41 DEBUG4: <class 'firewall.core.fw_transaction.FirewallTransaction'>.pre()
2020-03-20 22:27:41 DEBUG4: <class 'firewall.core.fw_transaction.FirewallTransaction'>.pre()
2020-03-20 22:27:41 DEBUG2: <class 'firewall.core.ipXtables.ip4tables'>: /sbin/iptables-restore /run/firewalld/temp.0ooke244: 116
       1: *security
       2: -F
       3: -X
       4: -Z
       5: COMMIT
       6: *raw
       7: -F
       8: -X
       9: -Z
      10: COMMIT
      11: *mangle
      12: -F
      13: -X
      14: -Z
      15: COMMIT
      16: *nat
      17: -F
      18: -X
      19: -Z
      20: COMMIT
      21: *filter
      22: -F
      23: -X
      24: -Z
      25: COMMIT
2020-03-20 22:27:41 DEBUG2: <class 'firewall.core.ipXtables.ip6tables'>: /sbin/ip6tables-restore /run/firewalld/temp.s6qbq300: 116
       1: *security
       2: -F
       3: -X
       4: -Z
       5: COMMIT
       6: *raw
       7: -F
       8: -X
       9: -Z
      10: COMMIT
      11: *mangle
      12: -F
      13: -X
      14: -Z
      15: COMMIT
      16: *nat
      17: -F
      18: -X
      19: -Z
      20: COMMIT
      21: *filter
      22: -F
      23: -X
      24: -Z
      25: COMMIT
2020-03-20 22:27:41 DEBUG2: <class 'firewall.core.ebtables.ebtables'>: /sbin/ebtables --concurrent -t nat -F
2020-03-20 22:27:41 DEBUG2: <class 'firewall.core.ebtables.ebtables'>: /sbin/ebtables --concurrent -t nat -X
2020-03-20 22:27:41 DEBUG2: <class 'firewall.core.ebtables.ebtables'>: /sbin/ebtables --concurrent -t nat -Z
2020-03-20 22:27:41 DEBUG2: <class 'firewall.core.ebtables.ebtables'>: /sbin/ebtables --concurrent -t filter -F
2020-03-20 22:27:41 DEBUG2: <class 'firewall.core.ebtables.ebtables'>: /sbin/ebtables --concurrent -t filter -X
2020-03-20 22:27:41 DEBUG2: <class 'firewall.core.ebtables.ebtables'>: /sbin/ebtables --concurrent -t filter -Z
2020-03-20 22:27:41 DEBUG2: <class 'firewall.core.nftables.nftables'>: /sbin/nft add table inet firewalld
2020-03-20 22:27:41 DEBUG2: <class 'firewall.core.nftables.nftables'>: /sbin/nft add table ip firewalld
2020-03-20 22:27:41 DEBUG2: <class 'firewall.core.nftables.nftables'>: /sbin/nft add table ip6 firewalld
2020-03-20 22:27:41 DEBUG4: <class 'firewall.core.fw_transaction.FirewallTransaction'>.post()
2020-03-20 22:27:41 DEBUG4: <class 'firewall.core.fw_transaction.FirewallTransaction'>.post()
2020-03-20 22:27:41 DEBUG1: Applying default rule set
2020-03-20 22:27:41 DEBUG4: <class 'firewall.core.fw_transaction.FirewallTransaction'>.execute(True)
2020-03-20 22:27:41 DEBUG4: <class 'firewall.core.fw_transaction.FirewallTransaction'>.prepare(True, ...)
2020-03-20 22:27:41 DEBUG4: <class 'firewall.core.fw_transaction.FirewallTransaction'>.prepare(True, ...)
2020-03-20 22:27:41 DEBUG4: <class 'firewall.core.fw_transaction.FirewallTransaction'>.pre()
2020-03-20 22:27:41 DEBUG4: <class 'firewall.core.fw_transaction.FirewallTransaction'>.pre()
2020-03-20 22:27:41 DEBUG2: <class 'firewall.core.nftables.nftables'>: /sbin/nft add chain inet firewalld raw_PREROUTING { type filter hook prerouting priority -290 ; }
…
2020-03-20 22:27:41 DEBUG2: <class 'firewall.core.nftables.nftables'>: /sbin/nft insert rule inet firewalld raw_PREROUTING icmpv6 type { nd-router-advert, nd-neighbor-solicit } accept
2020-03-20 22:27:41 DEBUG4: <class 'firewall.core.fw_transaction.FirewallTransaction'>.post()
2020-03-20 22:27:41 DEBUG4: <class 'firewall.core.fw_transaction.FirewallTransaction'>.post()
2020-03-20 22:27:41 DEBUG1: Applying used zones
2020-03-20 22:27:41 DEBUG1: Applying zone 'block'
2020-03-20 22:27:41 DEBUG1: Applying zone 'dmz'
2020-03-20 22:27:41 DEBUG1: Applying zone 'drop'
2020-03-20 22:27:41 DEBUG1: Applying zone 'external'
2020-03-20 22:27:41 DEBUG1: Applying zone 'home'
2020-03-20 22:27:41 DEBUG1: Applying zone 'internal'
2020-03-20 22:27:41 DEBUG1: Applying zone 'public'
2020-03-20 22:27:41 DEBUG1: Setting zone of interface 'ens3' to 'public'
2020-03-20 22:27:41 DEBUG1: Applying zone 'trusted'
2020-03-20 22:27:41 DEBUG1: Applying zone 'work'
2020-03-20 22:27:41 DEBUG4: <class 'firewall.core.fw_transaction.FirewallTransaction'>.execute(True)
2020-03-20 22:27:41 DEBUG4: <class 'firewall.core.fw_transaction.FirewallTransaction'>.prepare(True, ...)
2020-03-20 22:27:41 DEBUG4: <class 'firewall.core.fw_transaction.FirewallTransaction'>.prepare(True, ...)
2020-03-20 22:27:41 DEBUG4: <class 'firewall.core.fw_transaction.FirewallZoneTransaction'>.prepare(True, ...)
2020-03-20 22:27:41 DEBUG4: <class 'firewall.core.fw_transaction.FirewallZoneTransaction'>.prepare(True, ...)
2020-03-20 22:27:41 DEBUG4: <class 'firewall.core.fw_transaction.FirewallZoneTransaction'>.prepare(True, ...)
2020-03-20 22:27:41 DEBUG4: <class 'firewall.core.fw_transaction.FirewallZoneTransaction'>.prepare(True, ...)
2020-03-20 22:27:41 DEBUG4: <class 'firewall.core.fw_transaction.FirewallZoneTransaction'>.prepare(True, ...)
2020-03-20 22:27:41 DEBUG4: <class 'firewall.core.fw_transaction.FirewallZoneTransaction'>.prepare(True, ...)
2020-03-20 22:27:41 DEBUG4: <class 'firewall.core.fw_transaction.FirewallZoneTransaction'>.prepare(True, ...)
2020-03-20 22:27:41 DEBUG4: <class 'firewall.core.fw_transaction.FirewallZoneTransaction'>.prepare(True, ...)
2020-03-20 22:27:41 DEBUG4: <class 'firewall.core.fw_transaction.FirewallZoneTransaction'>.prepare(True, ...)
2020-03-20 22:27:41 DEBUG4: <class 'firewall.core.fw_transaction.FirewallZoneTransaction'>.prepare(True, ...)
2020-03-20 22:27:41 DEBUG4: <class 'firewall.core.fw_transaction.FirewallZoneTransaction'>.prepare(True, ...)
2020-03-20 22:27:41 DEBUG4: <class 'firewall.core.fw_transaction.FirewallZoneTransaction'>.prepare(True, ...)
2020-03-20 22:27:41 DEBUG4: <class 'firewall.core.fw_transaction.FirewallZoneTransaction'>.prepare(True, ...)
2020-03-20 22:27:41 DEBUG4: <class 'firewall.core.fw_transaction.FirewallZoneTransaction'>.prepare(True, ...)
2020-03-20 22:27:41 DEBUG4: <class 'firewall.core.fw_transaction.FirewallZoneTransaction'>.prepare(True, ...)
2020-03-20 22:27:41 DEBUG4: <class 'firewall.core.fw_transaction.FirewallZoneTransaction'>.prepare(True, ...)
2020-03-20 22:27:41 DEBUG4: <class 'firewall.core.fw_transaction.FirewallZoneTransaction'>.prepare(True, ...)
2020-03-20 22:27:41 DEBUG4: <class 'firewall.core.fw_transaction.FirewallZoneTransaction'>.prepare(True, ...)
2020-03-20 22:27:41 DEBUG4: <class 'firewall.core.fw_transaction.FirewallTransaction'>.pre()
2020-03-20 22:27:41 DEBUG4: <class 'firewall.core.fw_transaction.FirewallTransaction'>.pre()
2020-03-20 22:27:41 DEBUG4: <class 'firewall.core.fw_transaction.FirewallZoneTransaction'>.pre()
2020-03-20 22:27:41 DEBUG4: <class 'firewall.core.fw_transaction.FirewallZoneTransaction'>.pre()
2020-03-20 22:27:41 DEBUG4: <class 'firewall.core.fw_transaction.FirewallZoneTransaction'>.pre()
2020-03-20 22:27:41 DEBUG4: <class 'firewall.core.fw_transaction.FirewallZoneTransaction'>.pre()
2020-03-20 22:27:41 DEBUG4: <class 'firewall.core.fw_transaction.FirewallZoneTransaction'>.pre()
2020-03-20 22:27:41 DEBUG4: <class 'firewall.core.fw_transaction.FirewallZoneTransaction'>.pre()
2020-03-20 22:27:41 DEBUG4: <class 'firewall.core.fw_transaction.FirewallZoneTransaction'>.pre()
2020-03-20 22:27:41 DEBUG4: <class 'firewall.core.fw_transaction.FirewallZoneTransaction'>.pre()
2020-03-20 22:27:41 DEBUG4: <class 'firewall.core.fw_transaction.FirewallZoneTransaction'>.pre()
2020-03-20 22:27:41 DEBUG2: <class 'firewall.core.nftables.nftables'>: /sbin/nft add rule inet firewalld filter_OUTPUT index 0 ip6 daddr { ::0.0.0.0/96, ::ffff:0.0.0.0/96, 2002:0000::/24, 2002:0a00::/24, 2002:7f00::/24, 2002:ac10::/28, 2002:c0a8::/32, 2002:a9fe::/32, 2002:e000::/19, } reject with icmpv6 type addr-unreachable
2020-03-20 22:27:41 DEBUG2: <class 'firewall.core.nftables.nftables'>: /sbin/nft add rule inet firewalld filter_FORWARD index 2 ip6 daddr { ::0.0.0.0/96, ::ffff:0.0.0.0/96, 2002:0000::/24, 2002:0a00::/24, 2002:7f00::/24, 2002:ac10::/28, 2002:c0a8::/32, 2002:a9fe::/32, 2002:e000::/19, } reject with icmpv6 type addr-unreachable
2020-03-20 22:27:41 DEBUG2: <class 'firewall.core.nftables.nftables'>: /sbin/nft add chain inet firewalld raw_PRE_public
2020-03-20 22:27:41 DEBUG2: <class 'firewall.core.nftables.nftables'>: /sbin/nft add chain inet firewalld raw_PRE_public_pre
2020-03-20 22:27:41 DEBUG2: <class 'firewall.core.nftables.nftables'>: /sbin/nft add chain inet firewalld raw_PRE_public_log
2020-03-20 22:27:41 DEBUG2: <class 'firewall.core.nftables.nftables'>: /sbin/nft add chain inet firewalld raw_PRE_public_deny
2020-03-20 22:27:41 DEBUG2: <class 'firewall.core.nftables.nftables'>: /sbin/nft add chain inet firewalld raw_PRE_public_allow
2020-03-20 22:27:41 DEBUG2: <class 'firewall.core.nftables.nftables'>: /sbin/nft add chain inet firewalld raw_PRE_public_post
…
2020-03-20 22:27:42 DEBUG4: <class 'firewall.core.fw_transaction.FirewallTransaction'>.post()
2020-03-20 22:27:42 DEBUG4: <class 'firewall.core.fw_transaction.FirewallTransaction'>.post()
2020-03-20 22:27:42 DEBUG4: <class 'firewall.core.fw_transaction.FirewallZoneTransaction'>.post()
2020-03-20 22:27:42 DEBUG4: <class 'firewall.core.fw_transaction.FirewallZoneTransaction'>.post()
2020-03-20 22:27:42 DEBUG4: <class 'firewall.core.fw_transaction.FirewallZoneTransaction'>.post()
2020-03-20 22:27:42 DEBUG4: <class 'firewall.core.fw_transaction.FirewallZoneTransaction'>.post()
2020-03-20 22:27:42 DEBUG4: <class 'firewall.core.fw_transaction.FirewallZoneTransaction'>.post()
2020-03-20 22:27:42 DEBUG4: <class 'firewall.core.fw_transaction.FirewallZoneTransaction'>.post()
2020-03-20 22:27:42 DEBUG4: <class 'firewall.core.fw_transaction.FirewallZoneTransaction'>.post()
2020-03-20 22:27:42 DEBUG4: <class 'firewall.core.fw_transaction.FirewallZoneTransaction'>.post()
2020-03-20 22:27:42 DEBUG4: <class 'firewall.core.fw_transaction.FirewallZoneTransaction'>.post()
2020-03-20 22:27:42 DEBUG2: Flushing and applying took 0.621809 seconds
2020-03-20 22:27:42 DEBUG1: Setting policy to 'ACCEPT'
2020-03-20 22:27:42 DEBUG4: <class 'firewall.core.fw_transaction.FirewallTransaction'>.execute(True)
2020-03-20 22:27:42 DEBUG4: <class 'firewall.core.fw_transaction.FirewallTransaction'>.prepare(True, ...)
2020-03-20 22:27:42 DEBUG4: <class 'firewall.core.fw_transaction.FirewallTransaction'>.prepare(True, ...)
2020-03-20 22:27:42 DEBUG4: <class 'firewall.core.fw_transaction.FirewallTransaction'>.pre()
2020-03-20 22:27:42 DEBUG4: <class 'firewall.core.fw_transaction.FirewallTransaction'>.pre()
2020-03-20 22:27:42 DEBUG4: <class 'firewall.core.fw_transaction.FirewallTransaction'>.post()
2020-03-20 22:27:42 DEBUG4: <class 'firewall.core.fw_transaction.FirewallTransaction'>.post()
2020-03-20 22:27:42 DEBUG1: GetAll('org.fedoraproject.FirewallD1')
2020-03-20 22:27:42 DEBUG1: config.ipset.0.GetAll('org.fedoraproject.FirewallD1.config.ipset')
2020-03-20 22:27:42 DEBUG1: config.IPSetAdded('sshguard4')
2020-03-20 22:27:42 DEBUG1: config.ipset.1.GetAll('org.fedoraproject.FirewallD1.config.ipset')
2020-03-20 22:27:42 DEBUG1: config.IPSetAdded('sshguard6')
2020-03-20 22:27:42 DEBUG1: config.icmptype.0.GetAll('org.fedoraproject.FirewallD1.config.icmptype')
2020-03-20 22:27:42 DEBUG1: config.IcmpTypeAdded('address-unreachable')
…
2020-03-20 22:27:42 DEBUG1: config.icmptype.44.GetAll('org.fedoraproject.FirewallD1.config.icmptype')
2020-03-20 22:27:42 DEBUG1: config.IcmpTypeAdded('unknown-option')
2020-03-20 22:27:42 DEBUG1: config.service.0.GetAll('org.fedoraproject.FirewallD1.config.service')
2020-03-20 22:27:42 DEBUG1: config.ServiceAdded('RH-Satellite-6')
…
2020-03-20 22:27:42 DEBUG1: config.service.167.GetAll('org.fedoraproject.FirewallD1.config.service')
2020-03-20 22:27:42 DEBUG1: config.ServiceAdded('zabbix-server')
2020-03-20 22:27:42 DEBUG1: config.zone.0.GetAll('org.fedoraproject.FirewallD1.config.zone')
2020-03-20 22:27:42 DEBUG1: config.ZoneAdded('block')
…
2020-03-20 22:27:42 DEBUG1: config.zone.8.GetAll('org.fedoraproject.FirewallD1.config.zone')
2020-03-20 22:27:42 DEBUG1: config.ZoneAdded('work')
2020-03-20 22:27:42 DEBUG1: config.helper.0.GetAll('org.fedoraproject.FirewallD1.config.helper')
2020-03-20 22:27:42 DEBUG1: config.HelperAdded('Q.931')
…
2020-03-20 22:27:42 DEBUG1: config.helper.12.GetAll('org.fedoraproject.FirewallD1.config.helper')
2020-03-20 22:27:42 DEBUG1: config.HelperAdded('tftp')
2020-03-20 22:27:42 DEBUG1: config.GetAll('org.fedoraproject.FirewallD1.config')
```
Is there anything interesting in there? (I don't see anything…)

**Comment by nE0sIghT** [comment]
Ok, here is simpler test case:

```
#!/usr/bin/python3

from firewall.core.ipset import ipset

if __name__ == "__main__":
        ips = ipset()
        print(ips.set_list())
```

output:
```
Traceback (most recent call last):
  File "./test.py", line 8, in <module>
    print(ips.set_list())
  File "/usr/lib64/python3.6/site-packages/firewall/core/ipset.py", line 159, in set_list
    return self.__run(args).split("\n")
  File "/usr/lib64/python3.6/site-packages/firewall/core/ipset.py", line 86, in __run
    " ".join(_args), ret))
ValueError: '/sbin/ipset list' failed: 
```

**Comment by nE0sIghT** [comment]
firewalld expects ipset to be in /sbin, but Gentoo provide it in /usr/sbin

```
root@vortex tmp# LANG=C ./test.py 
[Errno 2] No such file or directory: '/sbin/ipset': '/sbin/ipset'
Traceback (most recent call last):
  File "./test.py", line 7, in <module>
    print(ips.set_list())
  File "/usr/lib64/python3.6/site-packages/firewall/core/ipset.py", line 159, in set_list
    return self.__run(args).split("\n")
  File "/usr/lib64/python3.6/site-packages/firewall/core/ipset.py", line 86, in __run
    " ".join(_args), ret))
ValueError: '/sbin/ipset list' failed: 
root@vortex tmp# which ipset
/usr/sbin/ipset
```

**Comment by nE0sIghT** [comment]
This is completelly Gentoo's misconfiguration: https://github.com/gentoo/gentoo/blob/master/net-firewall/firewalld/firewalld-0.7.3.ebuild#L79

**Comment by erig0** [comment]
@nE0sIghT, Thanks for tracking it down. Seems like a simple misconfigure. Closing this issue as this must be fixed in the ebuild.
