### ISSUE TITLE
firewall-cmd fails and blanks zone file

### ISSUE THREAD

**Issue by linuxdan** [firewalld/firewalld#773]
**What happened**:
```
[root@hostname zones]# firewall-cmd --permanent --add-icmp-block-inversion
Error: IO_Object_XMLGenerator instance has no attribute '_out'
[root@hostname zones]# firewall-cmd --permanent --add-icmp-block=echo-request
Error: IO_Object_XMLGenerator instance has no attribute '_out'
[root@hostname zones]# firewall-cmd --reload
success
[root@hostname zones]# firewall-cmd --list-all
drop (active)
  target: DROP
  icmp-block-inversion: no
  interfaces: enp0s31f6
  sources: 
  services: 
  ports: 
  protocols: 
  masquerade: no
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 
```
And the zone file, drop.xml, was wiped -- zero bytes

**What you expected to happen**:
A successful rule addition

**How to reproduce it (as minimally and precisely as possible)**:
Any firewall-cmd --permanent command

**Anything else we need to know?**:
Started happening a few days ago
```
2021-03-24 15:36:42 ERROR: Failed to load zone file '/etc/firewalld/zones/drop.xml': INVALID_ZONE: not a valid zone file: no element found: line 1, column 0
2021-03-24 15:36:56 ERROR: Failed to load zone file 'drop.xml': INVALID_ZONE: not a valid zone file: no element found: line 1, column 0
2021-03-24 16:06:55 ERROR: Failed to load zone file 'drop.xml': INVALID_ZONE: not a valid zone file: no element found: line 1, column 0
```
==> because it is a zero byte file

Adding debug to the config got:
```
2021-03-26 09:58:42 DEBUG1: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/firewall/server/decorators.py", line 68, in dbus_handle_exceptions
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/firewall/server/config_zone.py", line 227, in update
    self.obj = self.config.set_zone_config(self.obj, settings)
  File "/usr/lib/python2.7/site-packages/firewall/core/fw_config.py", line 739, in set_zone_config
    zone_writer(x)
  File "/usr/lib/python2.7/site-packages/firewall/core/io/zone.py", line 735, in zone_writer
    handler.startDocument()
  File "/usr/lib64/python2.7/site-packages/_xmlplus/sax/saxutils.py", line 239, in startDocument
    self._out.write('<?xml version="1.0" encoding="%s"?>\n' %
AttributeError: IO_Object_XMLGenerator instance has no attribute '_out'
```
**Environment**:
Linux hostname 3.10.0-1160.15.2.el7.x86_64 #1 SMP Wed Feb 3 15:06:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

CentOS Linux release 7.9.2009 (Core)
```
[root]# yum list installed | grep firewall
firewall-config.noarch                  0.6.3-12.el7                   @updates 
firewalld.noarch                        0.6.3-12.el7                   @updates 
firewalld-filesystem.noarch             0.6.3-12.el7                   @updates 
python-firewall.noarch                  0.6.3-12.el7                   @updates 
system-config-firewall-base.noarch      1.2.29-10.el7                  @base    
system-config-firewall-tui.noarch       1.2.29-10.el7                  @base    
```

**Comment by erig0** [comment]
This is a very old version of firewalld and no longer supported upstream. Furthermore I can not reproduce it on RHEL 7.9. The stack trace shows the error is coming from saxutils, not firewalld. Maybe you should file a bug with CentOS.

```
[root@rhel7 ~]# firewall-cmd --permanent --add-icmp-block-inversion
success
[root@rhel7 ~]# yum info firewalld
Installed Packages
Name        : firewalld
Arch        : noarch
Version     : 0.6.3
Release     : 12.el7

[root@rhel7 ~]# cat /etc/os-release 
NAME="Red Hat Enterprise Linux Server"
VERSION="7.9 (Maipo)"
```
