### ISSUE TITLE
firewall  does not support the newest python packeages on centos 8.

### ISSUE THREAD

**Issue by habwang** [firewalld/firewalld#845]
After updated python-pkgs on centos 8,the firewalld.service report error:

```
[root@localhost ~]# firewall-cmd --zone=public --add-port=9998/tcp --permanent
Traceback (most recent call last):
  File "/usr/bin/firewall-cmd", line 31, in <module>
    from firewall.client import FirewallClient, FirewallClientIPSetSettings, \
  File "/usr/lib/python3.6/site-packages/firewall/client.py", line 29, in <module>
    import slip.dbus
  File "/usr/lib/python3.6/site-packages/slip/dbus/__init__.py", line 8, in <module>
    from . import service
  File "/usr/lib/python3.6/site-packages/slip/dbus/service.py", line 30, in <module>
    from six import with_metaclass
ModuleNotFoundError: No module named 'six'
[root@localhost ~]# python3 -m pip install six
Requirement already satisfied: six in /usr/local/lib/python3.6/site-packages
```

**Comment by atc0005** [comment]
@habwang I ran into this today. The culprit ended up being a `/usr/bin/six.pyc` file. This seems to have been created by the VMware Perl SDK installation process. Go figure.

Once I removed that file, the error went away.
