### ISSUE TITLE
Cannot reload with firewall-cmd --reload

### ISSUE THREAD

**Issue by agross** [firewalld/firewalld#878]
**What happened**:

```sh
$ firewall-cmd --reload
Argument 1 does not allow None as a value
```

```
Nov 05 17:10:52 router firewalld[178828]: Traceback (most recent call last):
                                            File "/usr/lib/python3.10/site-packages/firewall/server/decorators.py", line 67, in _impl
                                              return func(*args, **kwargs)
                                            File "/usr/lib/python3.10/site-packages/firewall/server/firewalld.py", line 323, in reload
                                              self.fw.reload()
                                            File "/usr/lib/python3.10/site-packages/firewall/core/fw.py", line 1082, in reload
                                              for interface in nm_get_interfaces_in_zone(zone):
                                            File "/usr/lib/python3.10/site-packages/firewall/core/fw_nm.py", line 184, in nm_get_interfaces_in_zone
                                              if zone == nm_get_zone_of_connection(conn):
                                            File "/usr/lib/python3.10/site-packages/firewall/core/fw_nm.py", line 76, in nm_get_zone_of_connection
                                              con = nm_get_client().get_connection_by_uuid(connection)
                                          TypeError: Argument 1 does not allow None as a value
```

**What you expected to happen**:

Reloading works.

**How to reproduce it (as minimally and precisely as possible)**:

Not sure.

**Anything else we need to know?**:

**Environment**:
- Firewalld Version (if Fedora based `dnf info firewalld` or commit hash if developing from git `git log -n1 --format=format:"%H"`): Name         : firewalld
Version      : 1.0.1
Release      : 2.fc35
- Firewalld Backend (`cat /etc/firewalld/firewalld.conf | grep FirewallBackend`): FirewallBackend=nftables
- OS (e.g: `cat /etc/os-release`): Fedora Linux 35 (Server Edition)
- Others:

**Comment by stejoo** [comment]
I have the exact same issue and my journal shows the same error message.

My first thought was this was due to network connection profiles in NetworkManager not having their `connection.zone` property set. No something I usually set, but for this issue I did all of them: that did not resolve the issue.

Looking further my next guess is `nm_get_client().get_connection_by_uuid(connection)` needs a `connection` to be filled in. I have an interface that is not managed by NetworkManager, but is known to NetworkManager. It's a WireGuard connection to be precise and it's not managed by NetworkManager but by `wg-quick`.

Do you perhaps have a network connection that is not managed by NetworkManager @erig0 ? Just checking if we have that in common.

**Comment by agross** [comment]
@stejoo 

```
$ nmcli device status
DEVICE           TYPE       STATE                   CONNECTION      
ens224           ethernet   connected               dsl             
he-ipv6          iptunnel   connected               he-ipv6         
ens192           ethernet   connected               ens192          
wg0              wireguard  connected               wg0             
br-1e47a6e47d4b  bridge     connected (externally)  br-1e47a6e47d4b 
br-44fcda4c6ed7  bridge     connected (externally)  br-44fcda4c6ed7 
br-56c3c41f5f11  bridge     connected (externally)  br-56c3c41f5f11 
br-57ef00ed4954  bridge     connected (externally)  br-57ef00ed4954 
br-59230560b694  bridge     connected (externally)  br-59230560b694 
br-5aa6430872e4  bridge     connected (externally)  br-5aa6430872e4 
br-942df46826f3  bridge     connected (externally)  br-942df46826f3 
br-9d1e8f5fe604  bridge     connected (externally)  br-9d1e8f5fe604 
br-ae43bbb61068  bridge     connected (externally)  br-ae43bbb61068 
br-b1b24d34a722  bridge     connected (externally)  br-b1b24d34a722 
br-b864ab933805  bridge     connected (externally)  br-b864ab933805 
br-ca120ca395ae  bridge     connected (externally)  br-ca120ca395ae 
br-cdd7f7a3c3c4  bridge     connected (externally)  br-cdd7f7a3c3c4 
br-d43d8814e3f1  bridge     connected (externally)  br-d43d8814e3f1 
br-f42432356fa1  bridge     connected (externally)  br-f42432356fa1 
docker0          bridge     connected (externally)  docker0         
ppp0             ppp        disconnected            --              
veth0789da3      ethernet   unmanaged               --              
veth0b53394      ethernet   unmanaged               --              
veth1064a3a      ethernet   unmanaged               --              
veth1b467c9      ethernet   unmanaged               --              
veth1ddc928      ethernet   unmanaged               --              
veth21d8ae9      ethernet   unmanaged               --              
veth24c5713      ethernet   unmanaged               --              
veth264bb5b      ethernet   unmanaged               --              
veth28cc8fe      ethernet   unmanaged               --              
veth317e846      ethernet   unmanaged               --              
veth3368354      ethernet   unmanaged               --              
veth336d0ee      ethernet   unmanaged               --              
veth39dc15d      ethernet   unmanaged               --              
veth42e9c35      ethernet   unmanaged               --              
veth468e927      ethernet   unmanaged               --              
veth519de6c      ethernet   unmanaged               --              
veth5a351df      ethernet   unmanaged               --              
veth5cc8b3c      ethernet   unmanaged               --              
veth6082cdf      ethernet   unmanaged               --              
veth664d0e0      ethernet   unmanaged               --              
veth7609373      ethernet   unmanaged               --              
veth7ab8313      ethernet   unmanaged               --              
veth8986a3f      ethernet   unmanaged               --              
veth8e5c3f4      ethernet   unmanaged               --              
veth98ea3d8      ethernet   unmanaged               --              
veth995767f      ethernet   unmanaged               --              
veth9a79d2a      ethernet   unmanaged               --              
veth9bdcc5e      ethernet   unmanaged               --              
vetha86ea1f      ethernet   unmanaged               --              
vethab2aec7      ethernet   unmanaged               --              
vethaca59e8      ethernet   unmanaged               --              
vethafc9907      ethernet   unmanaged               --              
vethb3f7323      ethernet   unmanaged               --              
vethb64d5c1      ethernet   unmanaged               --              
vethb7d9711      ethernet   unmanaged               --              
vethbca17da      ethernet   unmanaged               --              
vethbf78c21      ethernet   unmanaged               --              
vethc5e6404      ethernet   unmanaged               --              
vethd243441      ethernet   unmanaged               --              
vethd288c1d      ethernet   unmanaged               --              
vethd2be0aa      ethernet   unmanaged               --              
vethd31d4ac      ethernet   unmanaged               --              
vethda6ab9e      ethernet   unmanaged               --              
vethdd53655      ethernet   unmanaged               --              
vethde0dc1f      ethernet   unmanaged               --              
vethed73559      ethernet   unmanaged               --              
vethed92f0e      ethernet   unmanaged               --              
vethf0020fa      ethernet   unmanaged               --              
vethf0b05a0      ethernet   unmanaged               --              
vethf572ccc      ethernet   unmanaged               --              
vethf790c96      ethernet   unmanaged               --              
ppp0-ifb         ifb        unmanaged               --              
sit0             iptunnel   unmanaged               --              
lo               loopback   unmanaged               --              

```

**Comment by stejoo** [comment]
So: yes, you do too :smile:

**Comment by erig0** [comment]
What version of NetworkManager are you using?

**Comment by stejoo** [comment]
Should be the current stable of Fedora 35 in my case:
```
$ rpm -q NetworkManager
NetworkManager-1.32.12-2.fc35.x86_64
```

**Comment by agross** [comment]
> `NetworkManager-1.32.12-2.fc35.x86_64`

Same here.

**Comment by agross** [comment]
```sh
$ nmcli c show wg0
connection.id:                          wg0
connection.uuid:                        e721b041-1cce-42af-bcea-ecaac11ba9eb
connection.stable-id:                   --
connection.type:                        wireguard
connection.interface-name:              wg0
connection.autoconnect:                 yes
connection.autoconnect-priority:        400
connection.autoconnect-retries:         -1 (default)
connection.multi-connect:               0 (default)
connection.auth-retries:                -1
connection.timestamp:                   1646944665
connection.read-only:                   no
connection.permissions:                 --
connection.zone:                        trusted
connection.master:                      --
connection.slave-type:                  --
connection.autoconnect-slaves:          -1 (default)
connection.secondaries:                 --
connection.gateway-ping-timeout:        0
connection.metered:                     unknown
connection.lldp:                        default
connection.mdns:                        -1 (default)
connection.llmnr:                       -1 (default)
connection.wait-device-timeout:         -1
ipv4.method:                            manual
ipv4.dns:                               --
ipv4.dns-search:                        --
ipv4.dns-options:                       --
ipv4.dns-priority:                      0
ipv4.addresses:                         192.168.168.1/24
ipv4.gateway:                           --
ipv4.routes:                            --
ipv4.route-metric:                      -1
ipv4.route-table:                       0 (unspec)
ipv4.routing-rules:                     --
ipv4.ignore-auto-routes:                no
ipv4.ignore-auto-dns:                   no
ipv4.dhcp-client-id:                    --
ipv4.dhcp-iaid:                         --
ipv4.dhcp-timeout:                      0 (default)
ipv4.dhcp-send-hostname:                yes
ipv4.dhcp-hostname:                     --
ipv4.dhcp-fqdn:                         --
ipv4.dhcp-hostname-flags:               0x0 (none)
ipv4.never-default:                     no
ipv4.may-fail:                          yes
ipv4.required-timeout:                  -1 (default)
ipv4.dad-timeout:                       -1 (default)
ipv4.dhcp-vendor-class-identifier:      --
ipv4.dhcp-reject-servers:               --
ipv6.method:                            manual
ipv6.dns:                               --
ipv6.dns-search:                        --
ipv6.dns-options:                       --
ipv6.dns-priority:                      0
ipv6.addresses:                         2001:470:98df:c0de::1/64
ipv6.gateway:                           --
ipv6.routes:                            --
ipv6.route-metric:                      -1
ipv6.route-table:                       0 (unspec)
ipv6.routing-rules:                     --
ipv6.ignore-auto-routes:                no
ipv6.ignore-auto-dns:                   no
ipv6.never-default:                     no
ipv6.may-fail:                          yes
ipv6.required-timeout:                  -1 (default)
ipv6.ip6-privacy:                       -1 (unknown)
ipv6.addr-gen-mode:                     stable-privacy
ipv6.ra-timeout:                        0 (default)
ipv6.dhcp-duid:                         --
ipv6.dhcp-iaid:                         --
ipv6.dhcp-timeout:                      0 (default)
ipv6.dhcp-send-hostname:                yes
ipv6.dhcp-hostname:                     --
ipv6.dhcp-hostname-flags:               0x0 (none)
ipv6.token:                             --
wireguard.private-key:                  <hidden>
wireguard.private-key-flags:            0 (none)
wireguard.listen-port:                  51820
wireguard.fwmark:                       0x0
wireguard.peer-routes:                  yes
wireguard.mtu:                          0
wireguard.ip4-auto-default-route:       -1 (default)
wireguard.ip6-auto-default-route:       -1 (default)
proxy.method:                           none
proxy.browser-only:                     no
proxy.pac-url:                          --
proxy.pac-script:                       --
GENERAL.NAME:                           wg0
GENERAL.UUID:                           e721b041-1cce-42af-bcea-ecaac11ba9eb
GENERAL.DEVICES:                        wg0
GENERAL.IP-IFACE:                       wg0
GENERAL.STATE:                          activated
GENERAL.DEFAULT:                        no
GENERAL.DEFAULT6:                       no
GENERAL.SPEC-OBJECT:                    --
GENERAL.VPN:                            no
GENERAL.DBUS-PATH:                      /org/freedesktop/NetworkManager/ActiveConnection/4
GENERAL.CON-PATH:                       /org/freedesktop/NetworkManager/Settings/4
GENERAL.ZONE:                           trusted
GENERAL.MASTER-PATH:                    --
IP4.ADDRESS[1]:                         192.168.168.1/24
IP4.GATEWAY:                            --
IP4.ROUTE[1]:                           dst = 192.168.168.0/24, nh = 0.0.0.0, mt = 50
IP4.ROUTE[2]:                           dst = 192.168.168.2/32, nh = 0.0.0.0, mt = 50
IP4.ROUTE[3]:                           dst = 192.168.168.3/32, nh = 0.0.0.0, mt = 50
IP6.ADDRESS[1]:                         2001:470:98df:c0de::1/64
IP6.ADDRESS[2]:                         fe80::24b7:b49:14f9:6a95/64
IP6.GATEWAY:                            --
IP6.ROUTE[1]:                           dst = 2001:470:98df:c0de::/64, nh = ::, mt = 50
IP6.ROUTE[2]:                           dst = fe80::/64, nh = ::, mt = 50
IP6.ROUTE[3]:                           dst = 2001:470:98df:c0de::2/128, nh = ::, mt = 50
IP6.ROUTE[4]:                           dst = 2001:470:98df:c0de::3/128, nh = ::, mt = 50
```

**Comment by erig0** [comment]
`nm_get_connection_of_interface()` is returning `None`, but I'm not sure why. There are many possibilities.

Any chance you can apply this patch that adds debug?

```diff
diff --git a/src/firewall/core/fw_nm.py b/src/firewall/core/fw_nm.py
index 0e38dd47e927..2f41d7a161b5 100644
--- a/src/firewall/core/fw_nm.py
+++ b/src/firewall/core/fw_nm.py
@@ -195,20 +195,24 @@ def nm_get_connection_of_interface(interface):
 
     device = nm_get_client().get_device_by_iface(interface)
     if device is None:
+        log.warning("get_device_by_iface(): interface = {}".format(interface))
         return None
 
     active_con = device.get_active_connection()
     if active_con is None:
+        log.warning("get_active_connection(): device = {}".format(device))
         return None
 
     try:
         con = active_con.get_connection()
         if con.get_flags() & NM.SettingsConnectionFlags.NM_GENERATED:
+            log.warning("get_flags(): con = {}, flags = {}".format(con, con.get_flags()))
             return None
     except AttributeError:
         # Prior to NetworkManager 1.12, we can only guess
         # that a connection was generated.
         if con.get_unsaved():
+            log.warning("get_unsaved() is True")
             return None
 
     return active_con.get_uuid()
```

**Comment by gkalmar** [comment]
Hi @erig0 
I have the same issue, so I applied your debug code.
Here is the result:
get_active_connection(): device = <NM.DevicePpp object at 0x7efe44f42fc0 (NMDevicePpp at 0x556fe34602d0)>

It seems like the problem is the ppp0 device which is disconnected and does not have an active connection.

**Comment by foliva** [comment]
Hi,
I have the same issue and I have a ppp0 device as well. Is there any workaround to this?

System info:
"Fedora Linux 37 (Server Edition)"

Name         : firewalld
Version      : 1.2.2
Release      : 1.fc37

FirewallBackend=nftables

Thanks,

**Comment by erig0** [comment]
I would love to add a test for this, but I don't know how to reproduce with dummy interfaces.

**Comment by erig0** [comment]
I still don't understand how this could happen.

The interface list is built by `nm_get_interfaces()` which calls NM API `get_active_connections()`. Then that same interface/device is used to call `get_active_connection()` which returns None. IMO, that's completely unexpected.

Perhaps this is actually a NetworkManager bug or nuance?

**Comment by cognoquest** [comment]
> Can someone try PR #1070? It skip interfaces without connection profiles.
> 
> I would love to add a test for this, but I don't know how to reproduce with dummy interfaces.

In theory you should be able to reproduce this. If you have an available interface (you do not have to connect)

`dnf install ppp NetworkManager-ppp`
`echo "plugin rp-pppoe.so" | sudo tee -a /etc/ppp/options`
`nmcli connection add type pppoe ifname <interface or device> con-name ppp0 autoconnect true username fakeuser password fakepsswd`
`nmcli connection modify ppp0 ipv6.method ignore`

Here is what my interfaces looks like ens160 is the device used for ppp0. Yours the device i.e. ens160 for me, should be disconnected:
`nmcli device status`
DEVICE  TYPE      STATE         CONNECTION
ens160  ethernet  connected     ppp0
ens192  ethernet  connected     ens192
ppp0    ppp       disconnected  --
lo      loopback  unmanaged     --

and if all goes well... you should be able to reproduce the problem.

**Comment by erig0** [comment]
So I tried to reproduce this with a dummy interface. More specifically I wanted to reproduce the `disconnected` device. But that's doesn't seem to trigger the bug on current code.

I have added a [test case](https://github.com/firewalld/firewalld/pull/1070/commits/d4b9f5a077e0f16948ac237a231608dc09a68dee) to #1070.

This command with #1070::

```
git revert 3365a84e236301eee732b8cc713d3b588c8c3e65 && make check-integration TESTSUITEFLAGS="-k gh878 -v -e"
```

The `git revert` is for unrolling the fix I suggested in #1070. It does not reproduce the problem.

---

```
# git revert 3365a84e236301eee732b8cc713d3b588c8c3e65 && make check-integration TESTSUITEFLAGS="-k gh878"
[master 401242b01f7a] Revert "fix(fw_nm): skip interfaces without a connection profile"
 Date: Tue Jan 24 18:57:42 2023 -0500
 1 file changed, 2 deletions(-)
make -C src/tests check-integration
make[1]: Entering directory '/root/build/home/remote/egarver/work/firewalld/01/src/tests'
/bin/sh './integration/testsuite' -k gh878 -j1 \
        AUTOTEST_PATH="src" \
        PYTHONPATH="/root/build/home/remote/egarver/work/firewalld/01/src:" \
        FIREWALLD_DEFAULT_CONFIG="/root/build/home/remote/egarver/work/firewalld/01/config"
## ----------------------------- ##
## firewalld 1.2.999 test suite. ##
## ----------------------------- ##
  3: interfaces without connection profile           ok

## ------------- ##
## Test results. ##
## ------------- ##

1 test was successful.
make[1]: Leaving directory '/root/build/home/remote/egarver/work/firewalld/01/src/tests'
```

**Comment by cybercrusher** [comment]
I am running Fedora 37 with
firewalld version: 1.2.3
nftables version 1.0.4
nmcli tool version 1.40.10-1.fc37

I am getting the same error as agross. I am trying to run up pppoe on one of my interfaces. This looks to happen as soon as the ppp0 connects. I can run the firewall-cmd --reload when the ppp0 is not connected.

**Comment by erig0** [comment]
We either need a working test case, or someone to manually verify that #1070 fixes the issue for them.

**Comment by cybercrusher** [comment]
I did try changing the fw_nm.py
        if not conn:
            continue

I could not get the firewalld service to start. I would just get an error
but I can try what you need to test. I am at work right now but I will be
home after 5 pm EST.

**Comment by kruzer** [comment]
Orange PI 5
Ubuntu 22.04.2 LTS
Firewalld 1.1.1

I have the same error message, after inserting or booting with an usb LTE modem.
```
--- fw_nm.py	2023-03-04 01:15:34.149174286 +0800
+++ /usr/lib/python3/dist-packages/firewall/core/fw_nm.py	2023-03-04 01:03:43.971630232 +0800
@@ -72,6 +72,8 @@
     @return zone string setting of connection, empty string if not set, None if connection is unknown
     """
     check_nm_imported()
+    if connection is None:
+        return None
 
     con = nm_get_client().get_connection_by_uuid(connection)
     if con is None:
```
After adding this two lines to fw_nm.py I can reload with no further issues. I hope it doesn't break anything :)

**Comment by cognoquest** [comment]
AlmaLinux 8.7 (Stone Smilodon)
Firewalld 0.9.3

Changes below are working for me also.
P.

--- fw_nm.py	2023-03-04 01:15:34.149174286 +0800
+++ /usr/lib/python3/dist-packages/firewall/core/fw_nm.py	2023-03-04 01:03:43.971630232 +0800
@@ -72,6 +72,8 @@
     @return zone string setting of connection, empty string if not set, None if connection is unknown
     """
     check_nm_imported()
+    if connection is None:
+        return None
 
     con = nm_get_client().get_connection_by_uuid(connection)
     if con is None:

**Comment by amachronic** [comment]
I think the real problem is `nm_get_client().get_device_by_iface()` expects an *interface* name, but firewalld's `nm_get_interfaces()` returns the *IP interface* names. Those are two different things in NetworkManager and this is why firewalld isn't able to lookup the device.

As far as I can tell, the interface name is something used internally by NetworkManager (what you see in nmcli) and the IP interface is what you see in "ip link". Usually, but not always, these are the same, but on my 4G modem, the NM interface is called **cdc-wdm0** and the IP interface is called **wwp0s20f0u3c2**.

IOW, the bug occurs whenever there are active connections on devices where NM interface != IP interface.

**Comment by erig0** [comment]
@amachronic, I tried this, but the [libnm client API][1] has only `get_device_by_iface()`. There is no `get_device_by_ip_iface()`

[1]: https://developer-old.gnome.org/libnm/stable/NMClient.html#nm-client-get-device-by-iface

**Comment by thom311** [comment]
> I tried this, but the [libnm client API](https://developer-old.gnome.org/libnm/stable/NMClient.html#nm-client-get-device-by-iface) has only `get_device_by_iface()`. There is no `get_device_by_ip_iface()`

That's true, but `nm_client_get_device_by_iface()` is very non-sophisticated. You can just reimplement it, especially in python that seems easy.

See the code here: https://gitlab.freedesktop.org/NetworkManager/NetworkManager/-/blob/ba4a9ea79a7568f52337813e61ce1171c3aa7dd2/src/libnm-client-impl/nm-client.c#L4912

```python
   dev = get_first(d for d in nmc.get_devices() if d.get_ip_iface() == iface, default=None)
```

**Comment by thom311** [comment]
It is not clear how this could be reproduced otherwise (e.g. with dummy devices). Most device types (ethernet, dummy) don't have a difference between `get_iface()` and `get_ip_iface()` (except, `get_ip_iface()` may return None, if the device is not activated).

I think to reproduce this, you need a device that makes a difference here. For example, pppoe, WWan or bluetooth.

**Comment by amachronic** [comment]
I submitted a PR with a fix (it's tested locally & works fine for me). But I'm not sure what the best way to add a test case would be, and I had a hard time following NM's code to figure out what devices can be affected by this bug. If anyone knows one aside from PPP / WWAN / Bluetooth -- all of which would add CI dependencies and/or are difficult to setup -- I'd be happy to add a test case.

**Comment by erig0** [comment]
> I submitted a PR with a fix (it's tested locally & works fine for me).

Thanks. It's almost identical to the change I wrote. :)

I'm still trying to get a working test case. I'll stack it on top of your PR when it's ready.

**Comment by erig0** [comment]
> I'm still trying to get a working test case. I'll stack it on top of your PR when it's ready.

I give up. I couldn't get a working test case. I'll merge #1092.
