### ISSUE TITLE
firewalld (firewall-cmd) error AttributeError: module 'collections' has no attribute 'Callable'

### ISSUE THREAD

**Issue by V70024** [firewalld/firewalld#990]
### I encountered this error during execution
```

┌─[root@id-531791]─[~]
└──╼ #firewall-cmd
Traceback (most recent call last):
  File "/usr/bin/firewall-cmd", line 31, in <module>
    from firewall.client import FirewallClient, FirewallClientIPSetSettings, \
  File "/usr/lib/python3/dist-packages/firewall/client.py", line 85, in <module>
    class FirewallClientZoneSettings(object):
  File "/usr/lib/python3/dist-packages/firewall/client.py", line 250, in FirewallClientZoneSettings
    def addIcmpBlockInversion(self):
  File "/usr/lib/python3/dist-packages/slip/dbus/polkit.py", line 106, in enable_proxy
    assert(func is None or isinstance(func, collections.Callable))
AttributeError: module 'collections' has no attribute 'Callable'
┌─[✗]─[root@id-531791]─[~]
└──╼ #/usr/bin/python3 --version
Python 3.10.5
┌─[root@id-531791]─[~]
└──╼ #ls /usr/bin/python*
/usr/bin/python2    /usr/bin/python3         /usr/bin/python3.10         /usr/bin/python3.8
/usr/bin/python2.7  /usr/bin/python3-config  /usr/bin/python3.10-config 

```
os ubuntu 20.04 server

**Comment by V70024** [comment]
**The problem is solved, I made a small change**

_file  /usr/lib/python3/dist-packages/slip/dbus/polkit.py_
```
۱۰۵ |
۱۰۶ |    # ssert(func is None or isinstance(func, collections.Callable)) 
۱۰۷ |    assert(func is None or isinstance(func, collections.abc.Callable))
۱۰۸ |
```

`collections.Callable` to `collections.abc.Callable
`

**Comment by TorontoMedia** [comment]
Dependency for python-slip was dropped in May of 2021 and that issue has been fixed upstream https://github.com/nphilipp/python-slip/commit/9b939c0b534c1b7958fa0a3c7aedf30bca910431.

Since your version of Ubuntu is still maintained, you could report this issue to the maintainers or update your distribution to a newer version.

**Comment by erig0** [comment]
As noted above, firewalld no longer depends on python-slip. So this bug is not present on the latest code.
